Java model classes generator
vtanja/JSD pull request #20
Opened 2021-03-31 14:40 UTC by veca22

2021-03-31 17:04 UTC, nikolina-sarenac approved these changes

2021-03-31 19:16 UTC, balsa-sarenac requested changes

2021-03-31 19:16 UTC, balsa-sarenac commented on sbag/generators/java/__init__.py
> +            return '{}'.format(property.name.capitalize())
This can be recuced to just 
``` python
return property.name.capitalize()
```

2021-04-01 09:00 UTC, veca22 commented on sbag/generators/java/__init__.py
> +            return '{}'.format(property.name.capitalize())
It works 👍

2021-04-01 10:50 UTC, vtanja approved these changes

2021-04-01 13:48 UTC, balsa-sarenac approved these changes

2021-04-01 13:48 UTC, merged