Feature implement backend service getall request
vtanja/JSD pull request #41
Opened 2021-04-09 17:08 UTC by vtanja

2021-04-09 17:14 UTC, veca22 approved these changes

2021-04-09 17:22 UTC, nikolina-sarenac approved these changes

2021-04-09 17:29 UTC, balsa-sarenac approved these changes

2021-04-09 17:36 UTC, balsa-sarenac requested changes
Add pagination

2021-04-10 15:16 UTC, balsa-sarenac approved these changes

2021-04-10 16:23 UTC, merged